### PR TITLE
Chernarus Training

### PR DESCRIPTION
**Pull request by yxpoh**
Made a Chernarus version of the training mission
Thought that the landscape of Chernarus would give
a different training perspective.

Moved markers to appropriate positions.
Redone CQC Indoor locations

Movement Practice now has more trees and defilade due to Chernarus
terrain.

Signed-off-by: Poh <yxpoh@yahoo.com.sg>

### CODE REVIEW

**Comment by ProfCupcake** [comment]
Is Chernarus really different enough to make this worth it? We're not even done adding to the Altis one yet. 

Perhaps a Zargabad variant would be better - its tight, middle-east urban environment is notably different.

**Comment by ProfCupcake** [comment]
Ooh, or maybe Tanoa. That whole "movement practice" scenario would be interesting in its thick jungles.

**Comment by yxpoh** [comment]
I didn't put in that much effort. If there is anything that took some effort, it was just walking around a building getting the coords, but other than that, it was just moving around the markers.

Nonetheless, Tanoa do sound good, but do the majority of us have it already?

**Comment by yxpoh** [comment]
I guess I just wanted to make a quick variant i guess. No meaning to it actually.

**Comment by ProfCupcake** [comment]
I'm more concerned with the fact that, if a new version is added, any future changes will have to be performed on both of them.

**Comment by yxpoh** [comment]
True. If that's the case, I guess we just ignore this.

**Comment by ProfCupcake** [comment]
Closing this PR, then. The branch may be useful to keep, though, since we may wish to do a Chernarus template further down the line.

**Pull request closed without merging**
